---

- include: install.yml
  when: not calibre_uninstall and not calibre_update
  
- include: update.yml
  when: calibre_update
  tags:
    - calibre_update

- include: uninstall.yml
  when: calibre_uninstall
  tags:
    - calibre_uninstall
